import { featuredModelAssets, imageAssets } from '@/lib/assets';

const now = '2026-05-15T00:00:00.000Z';

export const fallbackCategories = [
  {
    id: 'electric',
    slug: 'electric',
    name_en: 'Electric Water Heaters',
    name_zh: '电热水器',
    description_en: 'Instant and storage electric water heaters for home, apartment, and OEM programs.',
    description_zh: '适用于家庭、公寓和 OEM 项目的即热式与储水式电热水器。',
    icon: 'Zap',
    sort_order: 1,
    created_at: now,
  },
  {
    id: 'gas',
    slug: 'gas',
    name_en: 'Gas Water Heaters',
    name_zh: '燃气热水器',
    description_en: 'Instant gas water heaters with LPG and natural gas configuration support.',
    description_zh: '支持液化气和天然气配置的即热式燃气热水器。',
    icon: 'Flame',
    sort_order: 2,
    created_at: now,
  },
  {
    id: 'solar',
    slug: 'solar',
    name_en: 'Solar Water Heaters',
    name_zh: '太阳能热水器',
    description_en: 'Solar hot water systems for roof-mounted residential and light commercial projects.',
    description_zh: '适用于屋顶安装、住宅和轻商用场景的太阳能热水系统。',
    icon: 'Sun',
    sort_order: 3,
    created_at: now,
  },
  {
    id: 'heat-pump',
    slug: 'heat-pump',
    name_en: 'Heat Pump Water Heaters',
    name_zh: '空气能热泵热水器',
    description_en: 'Energy-saving air source heat pump systems for homes, apartments, and light commercial use.',
    description_zh: '适用于住宅、公寓和轻商用场景的节能空气能热泵系统。',
    icon: 'Thermometer',
    sort_order: 4,
    created_at: now,
  },
  {
    id: 'commercial',
    slug: 'commercial',
    name_en: 'Commercial Systems',
    name_zh: '商用热水系统',
    description_en: 'High-capacity central hot water systems for hotels, schools, factories, and facilities.',
    description_zh: '面向酒店、学校、工厂和公共设施的集中热水系统。',
    icon: 'Factory',
    sort_order: 5,
    created_at: now,
  },
];

export const fallbackProducts = [
  {
    id: 'fallback-product1',
    slug: 'glass-panel-instant-16l',
    name_en: 'Glass Panel Instant Gas Water Heater',
    name_zh: '玻璃面板即热燃气热水器',
    description_en: 'Premium glass-front instant gas water heater for distributors, apartment projects, and OEM programs.',
    description_zh: '适合经销、住宅项目和 OEM 方案的高端玻璃面板即热燃气热水器。',
    price: 699,
    category_id: 'gas',
    category_slug: 'gas',
    specifications: { capacity: '16L/min', gas: 'LPG/NG', installation: 'Wall-mounted', channel: 'B2B/OEM' },
    images: [...imageAssets.productModels.product1],
    stock_quantity: 80,
    stock_status: 'in_stock',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'fallback-product2',
    slug: 'slim-glass-instant-water-heater',
    name_en: 'Slim Glass Instant Water Heater',
    name_zh: '纤薄玻璃即热热水器',
    description_en: 'Slim wall-mounted instant water heater with clean front styling for export wholesale and private-label programs.',
    description_zh: '纤薄壁挂即热热水器，适合出口批发和自有品牌项目。',
    price: 679,
    category_id: 'gas',
    category_slug: 'gas',
    specifications: { capacity: '12-16L/min', gas: 'LPG/NG', installation: 'Wall-mounted', support: 'Private label' },
    images: [...imageAssets.productModels.product2],
    stock_quantity: 90,
    stock_status: 'in_stock',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'fallback-product3',
    slug: 'premium-vertical-glass-heater',
    name_en: 'Premium Vertical Glass Electric Heater',
    name_zh: '高端立式玻璃电热水器',
    description_en: 'Vertical glass-front electric heater for premium residential and apartment project supply.',
    description_zh: '面向高端住宅和公寓项目的立式玻璃面板电热水器。',
    price: 599,
    category_id: 'electric',
    category_slug: 'electric',
    specifications: { capacity: '40-80L', power: '1.5-2.5kW', installation: 'Vertical wall-mounted', finish: 'Glass panel' },
    images: [...imageAssets.productModels.product3],
    stock_quantity: 100,
    stock_status: 'in_stock',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'fallback-product4',
    slug: 'compact-digital-wall-heater',
    name_en: 'Compact Digital Wall-Mounted Heater',
    name_zh: '紧凑数显壁挂电热水器',
    description_en: 'Compact digital wall-mounted electric heater for small bathrooms, rental apartments, and OEM orders.',
    description_zh: '适合小浴室、出租公寓和 OEM 订单的紧凑数显壁挂电热水器。',
    price: 529,
    category_id: 'electric',
    category_slug: 'electric',
    specifications: { capacity: '30-60L', power: '1.5-2.0kW', installation: 'Wall-mounted', display: 'Digital' },
    images: [...imageAssets.productModels.product4],
    stock_quantity: 100,
    stock_status: 'in_stock',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'fallback-product5',
    slug: 'horizontal-storage-electric-heater',
    name_en: 'Horizontal Storage Electric Water Heater',
    name_zh: '横式储水电热水器',
    description_en: 'Classic horizontal storage electric water heater with flexible capacity and OEM appearance options.',
    description_zh: '经典横式储水电热水器，支持多容量和 OEM 外观配置。',
    price: 499,
    category_id: 'electric',
    category_slug: 'electric',
    specifications: { capacity: '40-100L', power: '1.5-2.5kW', installation: 'Horizontal wall-mounted', warranty: 'Project-based' },
    images: [...imageAssets.productModels.product5],
    stock_quantity: 120,
    stock_status: 'in_stock',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'fallback-product6',
    slug: 'digital-horizontal-storage-heater',
    name_en: 'Digital Horizontal Storage Heater',
    name_zh: '数显横式储水热水器',
    description_en: 'Digital horizontal storage water heater for apartments, bathrooms, and distributor stock programs.',
    description_zh: '适合公寓、浴室和经销库存计划的数显横式储水热水器。',
    price: 549,
    category_id: 'electric',
    category_slug: 'electric',
    specifications: { capacity: '50-100L', power: '1.5-2.5kW', display: 'Digital control', channel: 'Distributor/OEM' },
    images: [...imageAssets.productModels.product6],
    stock_quantity: 110,
    stock_status: 'in_stock',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'fallback-product7',
    slug: 'slim-vertical-storage-heater',
    name_en: 'Slim Vertical Storage Heater',
    name_zh: '纤薄立式储水热水器',
    description_en: 'Slim vertical storage heater for compact bathrooms, apartments, and retail showrooms.',
    description_zh: '适合紧凑浴室、公寓和零售展厅的纤薄立式储水热水器。',
    price: 579,
    category_id: 'electric',
    category_slug: 'electric',
    specifications: { capacity: '40-80L', installation: 'Vertical wall-mounted', profile: 'Slim cabinet', use: 'Residential' },
    images: [...imageAssets.productModels.product7],
    stock_quantity: 85,
    stock_status: 'in_stock',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'fallback-product8',
    slug: 'rounded-horizontal-storage-series',
    name_en: 'Rounded Horizontal Storage Series',
    name_zh: '圆角横式储水系列',
    description_en: 'Rounded horizontal storage heater series for home bathrooms, apartment projects, and OEM distributors.',
    description_zh: '圆角横式储水热水器系列，适合家庭浴室、公寓项目和 OEM 经销商。',
    price: 559,
    category_id: 'electric',
    category_slug: 'electric',
    specifications: { capacity: '50-100L', tank: 'Enamel option', installation: 'Horizontal wall-mounted', customization: 'Available' },
    images: [...imageAssets.productModels.product8],
    stock_quantity: 95,
    stock_status: 'in_stock',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'fallback-product9',
    slug: 'premium-gold-storage-heater',
    name_en: 'Premium Gold Storage Water Heater',
    name_zh: '香槟金储水热水器',
    description_en: 'Premium finish storage water heater for high-end residential and light commercial hot water matching.',
    description_zh: '高端外观储水热水器，适合住宅和轻商用热水系统配套。',
    price: 899,
    category_id: 'heat-pump',
    category_slug: 'heat-pump',
    specifications: { capacity: '80-150L', finish: 'Premium gold', application: 'Residential/light commercial', support: 'System matching' },
    images: [...imageAssets.productModels.product9],
    stock_quantity: 45,
    stock_status: 'in_stock',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'fallback-product10',
    slug: 'commercial-horizontal-hot-water-unit',
    name_en: 'Commercial Horizontal Hot Water Unit',
    name_zh: '商用横式热水单元',
    description_en: 'Horizontal hot water unit for hotels, apartments, schools, and multi-unit engineering projects.',
    description_zh: '适合酒店、公寓、学校和多机工程项目的横式热水单元。',
    price: 1299,
    category_id: 'commercial',
    category_slug: 'commercial',
    specifications: { application: 'Commercial/project', configuration: 'Multi-unit matching', support: 'Engineering selection', order: 'Bulk inquiry' },
    images: [...imageAssets.productModels.product10],
    stock_quantity: 35,
    stock_status: 'in_stock',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'fallback-compact-horizontal',
    slug: 'compact-horizontal-60l',
    name_en: 'Compact Horizontal Electric Water Heater',
    name_zh: '卧式储水电热水器',
    description_en: 'Wall-mounted electric storage heater with digital control and compact installation profile.',
    description_zh: '壁挂式储水电热水器，配备数字温控，适合紧凑安装空间。',
    price: 499,
    compare_price: 549,
    category_id: 'electric',
    category_slug: 'electric',
    specifications: { capacity: '40-80L', power: '1.5-2.5kW', installation: 'Wall-mounted', warranty: '5 years' },
    images: [...featuredModelAssets[0].gallery],
    stock_quantity: 80,
    stock_status: 'in_stock',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'fallback-digital-wall',
    slug: 'digital-wall-mounted-instant',
    name_en: 'Digital Wall-Mounted Instant Electric Heater',
    name_zh: '智能壁挂即热电热水器',
    description_en: 'Instant wall-mounted electric heater for kitchens, apartments, and OEM programs.',
    description_zh: '壁挂即热电热水器，适合厨房、公寓和 OEM 项目。',
    price: 599,
    category_id: 'electric',
    category_slug: 'electric',
    specifications: { type: 'Instant', display: 'Digital', channel: 'B2B/OEM' },
    images: [...featuredModelAssets[1].gallery],
    stock_quantity: 120,
    stock_status: 'in_stock',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'fallback-gas-instant',
    slug: 'gas-instant-water-heater',
    name_en: 'Instant Gas Water Heater',
    name_zh: '即热式燃气热水器',
    description_en: 'Instant gas water heater with LPG and natural gas configuration for distributor and project supply.',
    description_zh: '支持液化气和天然气配置的即热式燃气热水器，适合渠道和项目供货。',
    price: 699,
    category_id: 'gas',
    category_slug: 'gas',
    specifications: { capacity: '10-16L/min', gas: 'LPG/NG', protection: 'Flame failure protection' },
    images: [imageAssets.productGeneral.gasBoiler],
    stock_quantity: 90,
    stock_status: 'in_stock',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'fallback-solar',
    slug: 'solar-hot-water-roof-system',
    name_en: 'Roof-Mounted Solar Hot Water System',
    name_zh: '屋顶太阳能热水系统',
    description_en: 'Solar hot water system for residential and light commercial roof installations.',
    description_zh: '适用于住宅和轻商用屋顶安装的太阳能热水系统。',
    price: 1399,
    category_id: 'solar',
    category_slug: 'solar',
    specifications: { capacity: '150-300L', installation: 'Roof-mounted', backup: 'Electric optional' },
    images: [imageAssets.productGeneral.solarHeater, imageAssets.productGeneral.solarRoof],
    stock_quantity: 35,
    stock_status: 'in_stock',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'fallback-heat-pump',
    slug: 'air-source-heat-pump-water-heater',
    name_en: 'Air Source Heat Pump Water Heater',
    name_zh: '空气能热泵热水器',
    description_en: 'Energy-saving air source heat pump water heater for homes, apartments, and light commercial projects.',
    description_zh: '节能空气能热泵热水器，适合住宅、公寓和轻商用项目。',
    price: 1899,
    category_id: 'heat-pump',
    category_slug: 'heat-pump',
    specifications: { capacity: '150-500L', application: 'Residential/light commercial', support: 'Project matching' },
    images: [...featuredModelAssets[3].gallery],
    stock_quantity: 30,
    stock_status: 'in_stock',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'fallback-commercial-boiler',
    slug: 'commercial-boiler-system',
    name_en: 'Commercial Central Hot Water System',
    name_zh: '商用集中热水系统',
    description_en: 'Project-ready commercial hot water system for hotels, facilities, schools, and factories.',
    description_zh: '面向酒店、设施、学校和工厂项目的商用集中热水系统。',
    price: 2999,
    category_id: 'commercial',
    category_slug: 'commercial',
    specifications: { application: 'Commercial', support: 'Project inquiry', energy: 'Gas/Electric/Hybrid options' },
    images: [imageAssets.productGeneral.industrialBoiler, imageAssets.productGeneral.gasBoiler],
    stock_quantity: 20,
    stock_status: 'low_stock',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
];

export const fallbackArticles = [
  {
    id: 'fallback-factory-capability',
    slug: 'factory-capability',
    type: 'case_study',
    title_en: 'Factory Capability and Production Proof',
    title_zh: '工厂能力与生产证明',
    excerpt_en: 'How production scenes and qualification sheets support B2B buyer trust.',
    excerpt_zh: '生产场景和资质资料如何支撑 B2B 采购信任。',
    content_en:
      'Real factory imagery, reception photos, and qualification documents should be used as trust signals throughout the website.',
    content_zh: '真实工厂图、公司前台和资质资料应贯穿网站，作为采购商的信任信号。',
    featured_image: imageAssets.lifestyle.factoryProduction,
    is_published: true,
    created_at: now,
    published_at: now,
  },
  {
    id: 'fallback-hotel-solution',
    slug: 'hotel-hot-water-solution',
    type: 'case_study',
    title_en: 'Hotel Hot Water Supply Planning',
    title_zh: '酒店热水供应方案规划',
    excerpt_en: 'Match storage and commercial systems to guest room demand and maintenance cycles.',
    excerpt_zh: '根据客房需求和维护周期匹配储水式与商用热水系统。',
    content_en:
      'Hotels need stable supply, service access, and product families that can scale across rooms and facilities.',
    content_zh: '酒店项目需要稳定供应、便于维护，并能在客房和公共设施中规模化部署。',
    featured_image: imageAssets.lifestyle.hotel,
    is_published: true,
    created_at: now,
    published_at: now,
  },
];
