import { featuredModelAssets, imageAssets } from '@/lib/assets';

const now = '2026-05-15T00:00:00.000Z';

export const fallbackCategories = [
  {
    id: 'electric',
    slug: 'electric',
    name_en: 'Electric Heaters',
    name_zh: '电热水器',
    description_en: 'Instant and storage electric water heaters for home and project use.',
    description_zh: '适用于家庭和项目的即热式、储水式电热水器。',
    icon: 'Zap',
    sort_order: 1,
    created_at: now,
  },
  {
    id: 'storage',
    slug: 'storage',
    name_en: 'Storage Heaters',
    name_zh: '储水式热水器',
    description_en: 'Vertical and horizontal storage heaters with stable temperature control.',
    description_zh: '立式和卧式储水热水器，提供稳定温控。',
    icon: 'Thermometer',
    sort_order: 2,
    created_at: now,
  },
  {
    id: 'solar',
    slug: 'solar',
    name_en: 'Solar Heaters',
    name_zh: '太阳能热水系统',
    description_en: 'Solar hot water systems for roof-mounted applications.',
    description_zh: '适用于屋顶安装场景的太阳能热水系统。',
    icon: 'Sun',
    sort_order: 3,
    created_at: now,
  },
  {
    id: 'boiler',
    slug: 'boiler',
    name_en: 'Commercial Systems',
    name_zh: '商用热水系统',
    description_en: 'Boilers and high-capacity systems for commercial projects.',
    description_zh: '面向商用项目的锅炉和大容量热水系统。',
    icon: 'Factory',
    sort_order: 4,
    created_at: now,
  },
];

export const fallbackProducts = [
  {
    id: 'fallback-compact-horizontal',
    slug: 'compact-horizontal-60l',
    name_en: 'Compact Horizontal Electric Heater 60L',
    name_zh: '60L 卧式速热电热水器',
    description_en: 'Wall-mounted 60L electric heater with digital control and compact installation profile.',
    description_zh: '60L 壁挂式电热水器，配备数字控制，适合紧凑安装场景。',
    price: 499,
    compare_price: 549,
    category_id: 'electric',
    category_slug: 'electric',
    specifications: { capacity: '60L', installation: 'Wall-mounted', warranty: '5 years' },
    images: [...featuredModelAssets[0].gallery],
    stock_quantity: 80,
    stock_status: 'in_stock',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'fallback-digital-wall',
    slug: 'digital-wall-mounted-instant',
    name_en: 'Digital Wall-Mounted Instant Heater',
    name_zh: '智能壁挂即热热水器',
    description_en: 'Instant wall-mounted heater with visible controls for kitchens, apartments, and OEM programs.',
    description_zh: '带控制面板的壁挂即热热水器，适合厨房、公寓和 OEM 项目。',
    price: 599,
    category_id: 'electric',
    category_slug: 'electric',
    specifications: { type: 'Instant', display: 'Digital', channel: 'B2B/B2C' },
    images: [...featuredModelAssets[1].gallery],
    stock_quantity: 120,
    stock_status: 'in_stock',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'fallback-cylinder-series',
    slug: 'vertical-storage-cylinder',
    name_en: 'Vertical Storage Cylinder Series',
    name_zh: '立式储水圆筒系列',
    description_en: 'Vertical storage heater family for households and apartment projects.',
    description_zh: '面向家庭和公寓项目的立式储水热水器系列。',
    price: 699,
    category_id: 'storage',
    category_slug: 'storage',
    specifications: { capacity: '80-120L', type: 'Storage', control: 'Digital' },
    images: [...featuredModelAssets[2].gallery],
    stock_quantity: 60,
    stock_status: 'in_stock',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'fallback-solar',
    slug: 'solar-hot-water-roof-system',
    name_en: 'Solar Hot Water Roof System',
    name_zh: '屋顶太阳能热水系统',
    description_en: 'Solar hot water system for residential and light commercial roof installations.',
    description_zh: '适用于住宅和轻商用屋顶安装的太阳能热水系统。',
    price: 1399,
    category_id: 'solar',
    category_slug: 'solar',
    specifications: { type: 'Solar', installation: 'Roof-mounted', backup: 'Electric optional' },
    images: [imageAssets.productGeneral.solarHeater, imageAssets.productGeneral.solarRoof],
    stock_quantity: 35,
    stock_status: 'in_stock',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'fallback-commercial-boiler',
    slug: 'commercial-boiler-system',
    name_en: 'Commercial Boiler System',
    name_zh: '商用锅炉热水系统',
    description_en: 'Project-ready commercial boiler system for hotels, facilities, and factories.',
    description_zh: '面向酒店、设施和工厂项目的商用锅炉热水系统。',
    price: 2999,
    category_id: 'boiler',
    category_slug: 'boiler',
    specifications: { application: 'Commercial', support: 'Project inquiry', fuel: 'Gas/Electric options' },
    images: [imageAssets.productGeneral.gasBoiler, imageAssets.productGeneral.industrialBoiler],
    stock_quantity: 20,
    stock_status: 'low_stock',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
];

export const fallbackArticles = [
  {
    id: 'fallback-factory-capability',
    slug: 'factory-capability',
    type: 'case_study',
    title_en: 'Factory Capability and Production Proof',
    title_zh: '工厂能力与生产证明',
    excerpt_en: 'How production scenes and qualification sheets support B2B buyer trust.',
    excerpt_zh: '生产场景和资质资料如何支撑 B2B 买家信任。',
    content_en: 'Real factory imagery, reception photos, and qualification documents should be used as trust signals throughout the website.',
    content_zh: '真实工厂图、公司前台和资质资料应贯穿网站，作为买家信任信号。',
    featured_image: imageAssets.lifestyle.factoryProduction,
    is_published: true,
    created_at: now,
    published_at: now,
  },
  {
    id: 'fallback-hotel-solution',
    slug: 'hotel-hot-water-solution',
    type: 'case_study',
    title_en: 'Hotel Hot Water Supply Planning',
    title_zh: '酒店热水供应方案规划',
    excerpt_en: 'Match storage and commercial systems to guest room demand and maintenance cycles.',
    excerpt_zh: '根据客房需求和维护周期匹配储水式与商用热水系统。',
    content_en: 'Hotels need stable supply, service access, and product families that can scale across rooms and facilities.',
    content_zh: '酒店项目需要稳定供应、便于维护，并能在客房和公共设施中规模化部署。',
    featured_image: imageAssets.lifestyle.hotel,
    is_published: true,
    created_at: now,
    published_at: now,
  },
];
